name: app-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: project9_dev
          POSTGRES_USER: mof
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@master
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug
          extensions: pdo, pdo_pgsql
      - name: Install dependencies
        run: make install

      - name: Wait for PostgreSQL
        run: until pg_isready -h localhost -p 5432; do echo "Waiting for PostgreSQL..."; sleep 2; done
        
      - name: Set up database
        env:
          DATABASE_URL: postgresql://mof:postgres@localhost:5432/project9_dev
        run: psql -d $DATABASE_URL -f database.sql

      - name: Run lint
        run: make lint
        
      - name: Run tests
        env:
          DATABASE_URL: postgresql://mof:postgres@localhost:5432/project9_dev
        run: make test
        
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v5.0.0          
        env:
          # Set CC_TEST_REPORTER_ID as secret of your repo
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}

        with:
          # The report file must be there, otherwise Code Climate won't find it
          coverageCommand: make test-coverage
          coverageLocations: ${{github.workspace}}/build/logs/clover.xml:clover
